# -*- coding: utf-8 -*-
"""AI Drama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2AC49C95M-PGT99HGtGTUZnhKU8I0jd
"""

import os
import yaml

from typing import Optional, List, Dict

from pydantic import BaseModel, Field
from pathlib import Path
from pydub import AudioSegment

from google import genai
from google.genai import types

# --- Project Setup ---
ROOT_DIR = "/home/yufujimoto/Git/ai_drama_creator_3"

# -*- coding: utf-8 -*-
import os
import yaml
from typing import Optional, List, Dict


from generator import GenerateTextConfig, TtsGenerator, GeneratorVoiceConfig,LlmGenerator
from drama import Actor, Scene, AudioPrompt, GeminiVoice
from generate_transcript import generate_transcript_prompt


class Project:
    def __init__(self, 
                 root_dir: str, 
                 api_key: Optional[str] = None, 
                 actors: Optional[List[Actor]] = None, 
                 scenes: Optional[Dict[int, Scene]] = None,
                 tts_gen: Optional[TtsGenerator] = None,
                 llm_gen: Optional[LlmGenerator] = None,
                 tts_config: Optional[GeneratorVoiceConfig] = None,
                 llm_config: Optional[GenerateTextConfig] = None
                 ):
        self.api_key = api_key
        
        self.root_dir = root_dir
        if not os.path.exists(root_dir):
            os.makedirs(root_dir)
            print(f"Created root directory: {root_dir}")
        
        self.project_dir = os.path.join(root_dir, "project")
        if not os.path.exists(self.project_dir):
            self.create_project()
        else:
            print(f"Project directory already exists: {self.project_dir}")

        self.working_dirs = []
        self.working_dirs.append(("sound_path", os.path.join(self.project_dir, "sound")))
        self.working_dirs.append(("script_path", os.path.join(self.project_dir, "script")))
        self.working_dirs.append(("plot_path", os.path.join(self.project_dir, "plot")))
        self.working_dirs.append(("scene_path", os.path.join(self.project_dir, "scene")))

        self.check_directories()

        # GUI等から直接オブジェクトが渡された場合も考慮しつつ初期化
        # get_actorsが呼ばれた後は character_name をキーとした辞書に更新される仕様
        self.actors = {}
        if actors is not None:
            for actor in actors:
                self.actors[actor.character_name] = actor

        self.acts = []
        if scenes is not None:
            for order, scene in enumerate(scenes):
                self.acts.append((order, scene))
        
        self.tts_gen = tts_gen
        self.llm_gen = llm_gen
        self.tts_config = tts_config
        self.llm_config = llm_config
        
    def create_project(self):
        os.makedirs(self.project_dir, exist_ok=True)
        print(f"Created project directory: {self.project_dir}")
    
    def check_directories(self):
        for name, path in self.working_dirs:
            if not os.path.exists(path):
                os.makedirs(path)
                print(f"Created {name} at: {path}")
            else:
                print(f"{name} already exists at: {path}")

    def get_working_path(self, key: str) -> str:
        """working_dirsのタプルリストから特定のキーに対応するパスを返します"""
        for name, path in self.working_dirs:
            if name == key:
                return path
        return None
    
    def get_character_map(self) -> List[List[str]]:
        character_map = []
        for actor in project.actors.values():
            character_map.append([actor.character_name, actor.label])
        return character_map

    def set_actors_yaml(self, actors_yaml_path: str) -> Dict[str, Actor]:
        """
        YAMLファイルからアクター（役者）データをロードし、Actorオブジェクトの辞書を作成します。
        Key: character_name, Value: Actorオブジェクト
        """
        if not os.path.exists(actors_yaml_path):
            raise FileNotFoundError(f"[エラー] アクターYAMLファイルが見つかりません: {actors_yaml_path}")

        with open(actors_yaml_path, "r", encoding="utf-8") as f:
            actors_data = yaml.safe_load(f)

        if not actors_data or not isinstance(actors_data, list):
            raise ValueError(f"[エラー] {actors_yaml_path} のフォーマットが不正です。リスト形式で定義してください。")

        self.actors = {}
        for a_data in actors_data:
            # voiceが文字列で指定されている場合、GeminiVoice Enumに変換
            voice_str = a_data.get("voice")
            if isinstance(voice_str, str):
                try:
                    a_data["voice"] = GeminiVoice[voice_str]
                except KeyError:
                    print(f"Warning: ボイス '{voice_str}' は GeminiVoice に存在しません。デフォルトで ZEPHYR を割り当てます。")
                    a_data["voice"] = GeminiVoice.ZEPHYR

            # Actor インスタンスを生成
            actor_obj = Actor(**a_data)
            self.actors[actor_obj.character_name] = actor_obj

        print(f"Successfully loaded {len(self.actors)} actors from {actors_yaml_path}")
        return self.actors

    def set_scenes_yaml(self, order:int, scene_yaml_path: str) -> Scene:
        """
        YAMLファイルからシーンデータをロードし、
        あらかじめロードされているアクターマップ(self.actors)を元にSceneオブジェクトを構築します。
        """
        if not os.path.exists(scene_yaml_path):
            raise FileNotFoundError(f"[エラー] シーンYAMLファイルが見つかりません: {scene_yaml_path}")

        if not self.actors:
            raise ValueError("[エラー] シーンをロードする前に set_actors_yaml を実行してアクターデータを読み込んでください。")

        with open(scene_yaml_path, "r", encoding="utf-8") as f:
            scene_data = yaml.safe_load(f)

        if not scene_data or not isinstance(scene_data, dict):
            raise ValueError(f"[エラー] {scene_yaml_path} のフォーマットが不正です。辞書(Map)形式で定義してください。")

        # シーンの基本情報で初期化
        scene_obj = Scene(
            scene_id=scene_data["scene_id"],
            title=scene_data["title"]
        )

        # 各プロンプト（セリフ）のパース処理
        for p_data in scene_data.get("prompts", []):
            actor_name = p_data.pop("actor_name", None)
            if not actor_name:
                raise ValueError(f"[エラー] プロンプトデータに 'actor_name' が定義されていません: {p_data}")

            # 登録済みのアクターと紐付ける
            matched_actor = self.actors.get(actor_name)
            if not matched_actor:
                raise ValueError(
                    f"[整合性エラー] 原稿に登場するアクター '{actor_name}' は "
                    f"ロードされたアクターマップに存在しません。アクター定義を確認してください。"
                )

            # AudioPromptを生成してシーンに追加
            audio_prompt = AudioPrompt(
                actor=matched_actor,
                **p_data
            )
            scene_obj.add_prompt(audio_prompt)

        # 構築したシーンを管理リストへ登録
        self.acts.append((order, scene_obj))
        print(f"Successfully loaded Scene [{scene_obj.scene_id}]: '{scene_obj.title}' with {len(scene_obj.prompts)} prompts")
        return scene_obj

# --- Execution Block ---
if __name__ == "__main__":
    # Gemini APIキーの取得
    api_key = os.environ.get("GEMINI_API_KEY")
    
    # プロジェクト構造の初期化
    project = Project(
        root_dir=ROOT_DIR, 
        api_key=api_key
    )

    # 1. 必要なワーキングディレクトリのパスを取得
    plot_path = project.get_working_path("plot_path")
    scene_path = project.get_working_path("scene_path")
    script_path = project.get_working_path("script_path")
    sound_path = project.get_working_path("sound_path")

    # AIモデルの設定
    project.llm_gen = LlmGenerator(api_key=api_key)
    project.llm_gen = TtsGenerator(api_key=api_key, output_dir=sound_path)
    project.llm_config = GenerateTextConfig(
        thinking_level="MEDIUM", 
        temperature=0.7,
        system_instruction="あなたは優秀な音声ドラマの演出家です。簡潔に回答してください。"
    )
    project.tts_config = GeneratorVoiceConfig(
        temperature=1.0
    )


    if not plot_path or not scene_path:
        print(f"Error: Required directories not found (plot_path: {plot_path}, scene_path: {scene_path})")
        exit(1)

    # 2. アクター定義のロード (plot_path 内のすべての YAML ファイルを確実に読み込む)
    plot_files = sorted([f for f in os.listdir(plot_path) if f.endswith(('.yaml', '.yml'))])
    if not plot_files:
        print(f"Error: No YAML files found in plot_path: {plot_path}")
        exit(1)

    for file_name in plot_files:
        actors_file = os.path.join(plot_path, file_name)
        try:
            project.set_actors_yaml(actors_file)
        except Exception as e:
            print(f"Failed to load actors from {file_name}: {e}")
            exit(1)

    # 3. シーン（幕）定義のロード (scene_path 内のすべての YAML ファイルを名前順に確実に読み込む)
    scene_files = sorted([f for f in os.listdir(scene_path) if f.endswith(('.yaml', '.yml'))])
    if not scene_files:
        print(f"Error: No YAML files found in scene_path: {scene_path}")
        exit(1)

    # 自由なファイル名であっても、ソートされた順序（order）に従って acts に格納する
    for order, file_name in enumerate(scene_files):
        scene_file = os.path.join(scene_path, file_name)
        try:
            # set_scenes_yaml メソッドの内部で、すでに project.acts への追加が行われます。
            # そのため、戻り値を受け取るだけで、実行ブロック側で再度 append する必要はありません。
            my_scene = project.set_scenes_yaml(order, scene_file)
            
        except Exception as e:
            print(f"Failed to load scene from {file_name}: {e}")
            exit(1)
    

    # 3. プロンプトの自動生成
    transcript_file = os.path.join(script_path, "scene_01.txt")
    with open(transcript_file, "r", encoding="utf-8") as f:
        transcript = f.read()
    
    character_map = project.get_character_map()
    print(f"Character Map: {character_map}")

    generated_prompt = generate_transcript_prompt(character_map=character_map, transcript=transcript)
    print(f"Generated Prompt: {generated_prompt}")

    
    # response_text = project.llm_gen.generate_text(prompt_text=test_prompt, config=text_config)
    # project.tts_gen.run_scene(scene=my_scene, config=project.tts_config)
    

    